---
- hosts: localhost
  tasks:
   - name: terminate ec2 instance using Ansible
     ec2:
      state: 'absent'
      instance_id: i-0441d4320a110fcb3
      region: us-east-1
      wait: yes
      aws_access_key: *****************
      aws_secret_key: *********************
